# Generated by Django 5.1.6 on 2025-03-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('height', models.FloatField(help_text='Height in meters')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
